const express = require('express');
const router = express.Router();
const { getVultrChatResponse } = require('../controllers/vultrController');

/**
 * @swagger
 * /vultr/chat:
 *   post:
 *     summary: Get a chat response from the Vultr AI model for the Wellbee platform
 *     description: Sends a user query to the Vultr API using Wellbee's health and wellness context, and returns a relevant response.
 *     tags:
 *       - Vultr chat
 *     requestBody:
 *       required: true
 *       content:
 *         application/json:
 *           schema:
 *             type: object
 *             properties:
 *               userInput:
 *                 type: string
 *                 description: The user's input or question related to Wellbee
 *                 example: "What wellness tips can you provide for stress management?"
 *     responses:
 *       200:
 *         description: Successful response from the Vultr API
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 botMessage:
 *                   type: string
 *                   description: The response generated by the Vultr AI model based on Wellbee's context
 *                   example: "For stress management, Wellbee offers personalized wellness tips, including exercises and mood-boosting recommendations."
 *       500:
 *         description: An error occurred while fetching the response from the Vultr API
 */
router.post('/chat', getVultrChatResponse);

module.exports = router;
